--员工考勤表添加备注字段
ALTER TABLE T_EMPL_WORK ADD REMARK VARCHAR(3000);
ALTER TABLE T_EMPL_WORK MODIFY COLUMN REMARK VARCHAR(3000) COMMENT '备注';

--更改字段的长度
ALTER TABLE T_EMPL_WORK MODIFY COLUMN WORK_WAY VARCHAR(30) COMMENT '计算方式';

--添加菜单表字段
ALTER TABLE T_MENU ADD COLUMN IS_LEAF VARCHAR(3);
ALTER TABLE T_MENU MODIFY COLUMN IS_LEAF VARCHAR(3) COMMENT '是否为叶子(0:N;1:Y)';
ALTER TABLE T_MENU ADD COLUMN PARENT_ID INT(11);
ALTER TABLE T_MENU MODIFY COLUMN PARENT_ID INT(11) COMMENT '父节点ID';
ALTER TABLE T_MENU ADD COLUMN ROOT_ID INT(11);
ALTER TABLE T_MENU MODIFY COLUMN ROOT_ID INT(11) COMMENT '根节点ID';